package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import examdocs.BoardLevel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;

public class BoardSelector extends JFrame
        implements ActionListener {
    private JPanel mainPanel;
    private JPanel btnsPanel;
    private JLabel titleLabel;
    private JButton selectExamBoardButton;
    private ButtonGroup buttonGroup;

    public BoardSelector() {
        // Set JFrame properties
        setTitle("Exams Manager");
        setSize(400, 200);
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        buttonGroup = new ButtonGroup();

        for (BoardLevel level : BoardLevel.values()) {
            JRadioButton btn = new JRadioButton(level.toString());
            buttonGroup.add(btn);

            btnsPanel.add(btn, null);
        }

        selectExamBoardButton.addActionListener(this);

        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Enumeration<AbstractButton> enumeration = buttonGroup.getElements();
        int index = -1;
        boolean doneFlag = true;

        AbstractButton btn;
        do {
            btn = enumeration.nextElement();

            if (buttonGroup.getSelection().equals(btn.getModel())) {
                doneFlag = false;
            } else if (!enumeration.hasMoreElements()) {
                throw new RuntimeException();
            }
            index++;
        } while (doneFlag);

        BoardLevel level = BoardLevel.values()[index];

        AnchorListener anchorListener = new AnchorListener(level);
        anchorListener.getPage(Constants.VIEW_PAPERS);

        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        titleLabel = new JLabel();
        titleLabel.setText("Select exam board");
        mainPanel.add(titleLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnsPanel = new JPanel();
        btnsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.add(btnsPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        selectExamBoardButton = new JButton();
        selectExamBoardButton.setText("Select exam board");
        mainPanel.add(selectExamBoardButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
