package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import examdocs.ExamBoard;
import utils.FileHandler;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

public class ImportPaperPage extends JFrame
        implements ActionListener {

    private final ExamBoard board;
    private final AnchorListener finishedListener;

    private File examPaperFile = null;

    private JFileChooser fileChooser;
    private JPanel filePanel;
    private JLabel title;
    private JPanel mainPanel;

    public ImportPaperPage(ExamBoard board, AnchorListener finishedListener) {
        this.board = board;
        this.finishedListener = finishedListener;

        // Set JFrame properties
        $$$setupUI$$$();
        setTitle("Exams Manager - Split paper");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(mainPanel);

        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Document", "pdf"));
        fileChooser.addActionListener(this);

        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            case "CancelSelection" -> {
                finishedListener.getPage(Constants.VIEW_PAPERS);
                this.dispose();
            }

            case "ApproveSelection" -> {
                File chosenFile = fileChooser.getSelectedFile();

                if (!FileHandler.getFileExtension(chosenFile).equals("pdf")) {
                    return;
                }

                if (examPaperFile == null) {
                    examPaperFile = chosenFile;

                    title.setText("Choose mark scheme file to import");
                    fileChooser.setSelectedFile(chosenFile.getParentFile());
                    JOptionPane.showMessageDialog(
                            this,
                            "Exam paper saved, please select mark scheme"
                    );
                } else {
                    String name = JOptionPane.showInputDialog("Name of new exam:");
                    name = name.strip().replaceAll(" ", "-");

                    new SplitPaperPage(board.addPaper(examPaperFile, chosenFile, name), finishedListener);
                    this.dispose();
                }
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        title = new JLabel();
        title.setText("Choose exam paper file to import");
        mainPanel.add(title, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filePanel = new JPanel();
        filePanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(filePanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        fileChooser = new JFileChooser();
        filePanel.add(fileChooser, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
